"""Defines the different agents of the workflow.

The BaseAgent class defines an agent based on a provided prompt template, with a method `send_llm_request` for calling the Azure model. Also provides a class PlanStep, for parsing and working with the planned steps generated by the detailed planning agent.
"""

import json
from abc import ABC, abstractmethod
from collections.abc import Callable
from traceback import format_exc
from types import ModuleType
from typing import Generator

import json_repair
from langchain_core.messages import HumanMessage
from langchain_core.prompts import HumanMessagePromptTemplate

from config.prompts.tools import get_relevant_tool_desc
from llm_client import deploymentNames, yield_llm_client
from logger.logger import logging_decorator
from prompt_templates import Agent, AgentPromptTemplate


class PlanStep:
    """
    Defines the content of a single step in the plan. Initialized from an LLM output plan string.
    """

    def __init__(
        self,
        name: str,
        question: str,
        tool: Callable,
        parameters: dict[str],
        dependencies: list[str] = [],
    ):
        self.name = name
        self.question = question
        self.tool = tool
        self.parameters = parameters
        self.dependencies = dependencies
        self.executed = False

    def __repr__(self):
        return json.dumps(
            {
                "name": self.name,
                "question": self.question,
                "tool": self.tool.__name__,
                "parameters": self.parameters,
                "dependencies": self.dependencies,
                "executed": self.executed,
            },
            indent=2,
        )

    @staticmethod
    def plan_step_iterator(plan: str, tool_module: ModuleType) -> Generator:
        """
        Parse an LLM-generated plan into an iterator of individual PlanSteps. Skips any planned step with no tool call.
        """

        def _from_llm_output(llm_plan_step: dict[str]):
            name = llm_plan_step["name"]
            question = llm_plan_step["question"]
            try:
                tool = getattr(tool_module, llm_plan_step["tool"])
            except KeyError:
                print(format_exc())
                raise KeyError
            parameters = llm_plan_step["parameters"]
            dependencies = llm_plan_step["dependencies"]
            return PlanStep(name, question, tool, parameters, dependencies)

        try:
            plan_json = json_repair.loads(plan)
        except Exception:  # Unrecoverable JSON.
            print(format_exc())
            raise json.JSONDecodeError
        seen_parameters = set()
        for step in plan_json["steps"]:
            if (step["tool"] is not None) and (step["tool"] != "null"):
                filtered_params = json.dumps(
                    {
                        k: v
                        for k, v in step["parameters"].items()
                        if k not in ["fl", "rows", "sort", "facet_limit"]
                    }
                )
                if filtered_params not in seen_parameters:
                    seen_parameters.add(filtered_params)
                    yield _from_llm_output(step)
                else:
                    print("***`plan_step_iterator`: Skipping redundant step.")
                    continue
            else:
                print(
                    "***`plan_step_iterator`: Skipping step with no tool call specified."
                )
                continue


class BaseAgentV3(ABC):
    def __init__(self, agent: Agent):
        self.agent = agent
        self.model_name = None

    def get_prompt(
        self, conversation_history: list[dict] = None, tools_responses: list[str] = None
    ):
        if conversation_history is None:
            conversation_history = []
        if tools_responses is None:
            tools_responses = []
        assistant_template = AgentPromptTemplate(self.agent, "3.1")
        for conversation in conversation_history:
            assistant_template.add_user_template(conversation.query)
            assistant_template.add_ai_template(conversation.summary)
        for tool_response in tools_responses:
            assistant_template.add_ai_template(tool_response)
        return assistant_template.get_prompt_template()

    @staticmethod
    def get_user_template(message: str, input_variables=None):
        return HumanMessagePromptTemplate.from_template(
            template=f"""{message}""", input_variables=input_variables
        )

    # @logging_decorator(file_dumping=True, timing=True, printing=True, eval_track=True)
    @staticmethod
    def send_llm_request(
        messages: list,
        model: str,
        max_tokens: int = None,
        response_format: dict = None,
        tools: list[dict] = None,
    ):
        if tools is not None:
            llm_client = yield_llm_client(
                deployment_name=model, temperature=0
            ).bind_tools(tools=tools, tool_choice="auto")
            return llm_client.invoke(messages).tool_calls
        else:
            llm_client = yield_llm_client(
                deployment_name=model, temperature=0, max_tokens=max_tokens
            )
            if response_format:
                llm_client = llm_client.bind(response_format=response_format)
            return llm_client.invoke(messages).content

    @abstractmethod
    def execute(self):
        pass


class HighLevelPlanningAgentV3(BaseAgentV3):
    def __init__(self, query: str):
        super().__init__(agent=Agent.HIGH_LEVEL_PLANNING_AGENT)
        self.query = query
        self.model_name = deploymentNames.GPT_4O_MINI.value

    def execute(self):
        prompt = self.get_prompt()
        messages = prompt.format_messages(query=self.query)
        response_message = BaseAgentV3.send_llm_request(
            messages=messages,
            model=self.model_name,
            max_tokens=300,
            response_format={"type": "json_object"},
        )
        return response_message


class PlanningAgentV3(BaseAgentV3):
    def __init__(self, query: str, high_level_steps: list[str], entity_ids: list[dict]):
        super().__init__(agent=Agent.PLANNING_AGENT)
        self.query = query
        self.high_level_steps = high_level_steps
        self.entity_ids = entity_ids
        self.model_name = deploymentNames.GPT_4O.value

    def execute(self):
        prompt_params = {
            "high_level_steps": json.dumps(self.high_level_steps),
            "entity_ids": json.dumps(self.entity_ids),
            "user_query_message": self.query,
        }
        messages = self.get_prompt().format_messages(**prompt_params)
        response_message = BaseAgentV3.send_llm_request(
            messages=messages,
            model=self.model_name,
            max_tokens=2000,
            response_format={"type": "json_object"},
        )
        return response_message


class ActionAgentV3(BaseAgentV3):
    def __init__(self, plan_step: PlanStep, tools_responses: list[str]):
        super().__init__(agent=Agent.ACTION_AGENT)
        self.plan_step = plan_step
        self.tools_responses = tools_responses
        self.model_name = deploymentNames.GPT_4O_MINI.value

    def execute(self):
        prompt = (
            self.get_prompt()
            + [HumanMessage(content=str(self.plan_step))]
            + self.tools_responses
        )
        messages = prompt.format_messages()
        tool_calls = BaseAgentV3.send_llm_request(
            messages=messages,
            model=self.model_name,
            tools=get_relevant_tool_desc(self.plan_step.tool.__name__),
        )
        return tool_calls


class WritingAgentV3(BaseAgentV3):
    def __init__(
        self,
        query: str,
        data: list[str],
        conversation_history: list[dict] = None,
    ):
        super().__init__(agent=Agent.WRITING_AGENT)
        self.query = query
        self.conversation_history = conversation_history
        self.data = data
        self.model_name = deploymentNames.GPT_4O_MINI.value

    def execute(self):
        if self.data is None:
            self.data = [HumanMessage(content="Data missing.")]
        prompt = (
            self.get_prompt() + [BaseAgentV3.get_user_template(self.query)] + self.data
        )
        messages = prompt.format_messages()
        response_message = BaseAgentV3.send_llm_request(
            messages=messages,
            model=self.model_name,
            max_tokens=2000,
        )
        return response_message
